### ISSUE TITLE
several countries wrongly located in Asia

### ISSUE THREAD

**Issue by landroni** [xenotropic/quizzn#1]
I've played with the app today and I must admit that I was surprised to see Moldova within Europe, but Ukraine and Estonia in Asia Pacific. Estonia is even part of the EU. Most countries bordered by Russia to the East are usually placed within Europe. Russia is  border case by itself, but linguistically, historically and culturally it is much more part of Europe than of Asia (even though a majority of its territory is Asian).

**Comment by xenotropic** [comment]
Thanks. This is now fixed in the github source for all three (Russia, Ukraine, Estonia), but not going to do push out to the version on Google Play given the low number of downloads happening there.
